server:
  port: 30010
spring:
  application:
    name: integrated-gateway
  cloud:
    nacos:
      config:
        server-addr: nacos-server:8848
        group: integrated-example
        file-extension: yaml
      discovery:
        server-addr: nacos-server:8848
        group: integrated-example
    gateway:
      routes:
        - id: placeOrder
          uri: lb://integrated-order
          predicates:
            - Path=/order/create
        - id: queryStorage
          uri: lb://integrated-storage
          predicates:
            - Path=/storage/
        - id: queryAccount
          uri: lb://integrated-account
          predicates:
            - Path=/account/
        - id: praiseItemRocketMQ
          uri: lb://integrated-provider
          predicates:
            - Path=/praise/rocketmq
        - id: praiseItemSentinel
          uri: lb://integrated-provider
          predicates:
            - Path=/praise/sentinel
        - id: queryPraise
          uri: lb://integrated-consumer
          predicates:
            - Path=/praise/query

  config:
    import: optional:nacos:integrated-gateway.yaml