server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.168.0.211:3306/steam
    username: root
    password: 123456

logging:
  level:
    com.xxx: debug
    com.xxx.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: org.example.model
