// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: version_object_proto.proto
// Protobuf Java Version: 4.32.0

package com.yuhoutian.protobuf.demo.model;

@com.google.protobuf.Generated
public final class VersionObjectProto {
  private VersionObjectProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      VersionObjectProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VersionObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yuhoutian.protobuf.demo.model.VersionObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 version = 1;</code>
     * @return The version.
     */
    long getVersion();

    /**
     * <code>.google.protobuf.Any obj = 2;</code>
     * @return Whether the obj field is set.
     */
    boolean hasObj();
    /**
     * <code>.google.protobuf.Any obj = 2;</code>
     * @return The obj.
     */
    com.google.protobuf.Any getObj();
    /**
     * <code>.google.protobuf.Any obj = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getObjOrBuilder();
  }
  /**
   * Protobuf type {@code com.yuhoutian.protobuf.demo.model.VersionObject}
   */
  public static final class VersionObject extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.yuhoutian.protobuf.demo.model.VersionObject)
      VersionObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        VersionObject.class.getName());
    }
    // Use VersionObject.newBuilder() to construct.
    private VersionObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VersionObject() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuhoutian.protobuf.demo.model.VersionObjectProto.internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuhoutian.protobuf.demo.model.VersionObjectProto.internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject.class, com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_ = 0L;
    /**
     * <code>int64 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    public static final int OBJ_FIELD_NUMBER = 2;
    private com.google.protobuf.Any obj_;
    /**
     * <code>.google.protobuf.Any obj = 2;</code>
     * @return Whether the obj field is set.
     */
    @java.lang.Override
    public boolean hasObj() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Any obj = 2;</code>
     * @return The obj.
     */
    @java.lang.Override
    public com.google.protobuf.Any getObj() {
      return obj_ == null ? com.google.protobuf.Any.getDefaultInstance() : obj_;
    }
    /**
     * <code>.google.protobuf.Any obj = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getObjOrBuilder() {
      return obj_ == null ? com.google.protobuf.Any.getDefaultInstance() : obj_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0L) {
        output.writeInt64(1, version_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getObj());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, version_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getObj());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject)) {
        return super.equals(obj);
      }
      com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject other = (com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (hasObj() != other.hasObj()) return false;
      if (hasObj()) {
        if (!getObj()
            .equals(other.getObj())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      if (hasObj()) {
        hash = (37 * hash) + OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getObj().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yuhoutian.protobuf.demo.model.VersionObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yuhoutian.protobuf.demo.model.VersionObject)
        com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yuhoutian.protobuf.demo.model.VersionObjectProto.internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yuhoutian.protobuf.demo.model.VersionObjectProto.internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject.class, com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject.Builder.class);
      }

      // Construct using com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetObjFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        version_ = 0L;
        obj_ = null;
        if (objBuilder_ != null) {
          objBuilder_.dispose();
          objBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yuhoutian.protobuf.demo.model.VersionObjectProto.internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_descriptor;
      }

      @java.lang.Override
      public com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject getDefaultInstanceForType() {
        return com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject.getDefaultInstance();
      }

      @java.lang.Override
      public com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject build() {
        com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject buildPartial() {
        com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject result = new com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.obj_ = objBuilder_ == null
              ? obj_
              : objBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject) {
          return mergeFrom((com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject other) {
        if (other == com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject.getDefaultInstance()) return this;
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        if (other.hasObj()) {
          mergeObj(other.getObj());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                version_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    internalGetObjFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long version_ ;
      /**
       * <code>int64 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <code>int64 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {

        version_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any obj_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> objBuilder_;
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       * @return Whether the obj field is set.
       */
      public boolean hasObj() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       * @return The obj.
       */
      public com.google.protobuf.Any getObj() {
        if (objBuilder_ == null) {
          return obj_ == null ? com.google.protobuf.Any.getDefaultInstance() : obj_;
        } else {
          return objBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       */
      public Builder setObj(com.google.protobuf.Any value) {
        if (objBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          obj_ = value;
        } else {
          objBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       */
      public Builder setObj(
          com.google.protobuf.Any.Builder builderForValue) {
        if (objBuilder_ == null) {
          obj_ = builderForValue.build();
        } else {
          objBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       */
      public Builder mergeObj(com.google.protobuf.Any value) {
        if (objBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            obj_ != null &&
            obj_ != com.google.protobuf.Any.getDefaultInstance()) {
            getObjBuilder().mergeFrom(value);
          } else {
            obj_ = value;
          }
        } else {
          objBuilder_.mergeFrom(value);
        }
        if (obj_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       */
      public Builder clearObj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        obj_ = null;
        if (objBuilder_ != null) {
          objBuilder_.dispose();
          objBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       */
      public com.google.protobuf.Any.Builder getObjBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetObjFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getObjOrBuilder() {
        if (objBuilder_ != null) {
          return objBuilder_.getMessageOrBuilder();
        } else {
          return obj_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : obj_;
        }
      }
      /**
       * <code>.google.protobuf.Any obj = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          internalGetObjFieldBuilder() {
        if (objBuilder_ == null) {
          objBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getObj(),
                  getParentForChildren(),
                  isClean());
          obj_ = null;
        }
        return objBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.yuhoutian.protobuf.demo.model.VersionObject)
    }

    // @@protoc_insertion_point(class_scope:com.yuhoutian.protobuf.demo.model.VersionObject)
    private static final com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject();
    }

    public static com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VersionObject>
        PARSER = new com.google.protobuf.AbstractParser<VersionObject>() {
      @java.lang.Override
      public VersionObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VersionObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VersionObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yuhoutian.protobuf.demo.model.VersionObjectProto.VersionObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032version_object_proto.proto\022!com.yuhout" +
      "ian.protobuf.demo.model\032\031google/protobuf" +
      "/any.proto\"C\n\rVersionObject\022\017\n\007version\030\001" +
      " \001(\003\022!\n\003obj\030\002 \001(\0132\024.google.protobuf.Anyb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_yuhoutian_protobuf_demo_model_VersionObject_descriptor,
        new java.lang.String[] { "Version", "Obj", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
